### ISSUE TITLE
lightningd: SQLITE version mismatch: compiled 3031001, now 3035005

### ISSUE THREAD

**Issue by arcbtc** [fiatjaf/trustedcoin#11]
Installed using,
https://github.com/fiatjaf/trustedcoin#extra-how-to-bootstrap-a-lightning-node-from-scratch-without-bitcoin-core-on-ubuntu-amd64

After a server restart, now getting `lightningd: SQLITE version mismatch: compiled 3031001, now 3035005`

Found this, https://github.com/ElementsProject/lightning/issues/1497 

Do I need to recompile trustedcoin_linux_amd64?

Whats the safest way to get it running?

**Comment by fiatjaf** [comment]
Sorry, I didn't see this a million years ago when it was created.

But that is not related to trustedcoin.
