### ISSUE TITLE
Request: GPG-sign releases or commits

### ISSUE THREAD

**Issue by erikarvstedt** [fiatjaf/trustedcoin#12]
While packaging trustedcoin for [nix-bitcoin](https://github.com/fort-nix/nix-bitcoin/pull/533), where we use signature checking for all package releases, I noticed that trustedcoin provides no signatures at all.
Could you add sigs? This would remove Github as a trusted party for distributing trustedcoin.

(Yes, it's slightly amusing to request this for a package like trustedcoin.)

**Comment by fiatjaf** [comment]
I have no idea of how to do this. Is there a guide somewhere? Do the signatures have to be in some special place or something like that? What about the key?

**Comment by erikarvstedt** [comment]
1. If you don't have a GPG key, [generate it](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key),
2. [Add the key to GitHub](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account)
3. Follow section [Telling Git about your GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key-1)
4. Publish the pubkey to keyservers:
```bash
# key is the same hex string that you used in `git config --global user.signingkey <key>`
key=<key id>
gpg --send-keys --keyserver hkps://keys.openpgp.org $key
gpg --send-keys --keyserver hkps://keyserver.ubuntu.com $key
```
5. To sign all future commits in a git repo, run `git config commit.gpgsign true` in the repo.
To sign all future commits in all repos, configure it globally: `git config --global commit.gpgsign true`

**Comment by fiatjaf** [comment]
Thank you for the guide. I think this should be done. Let me know if not.

**Comment by erikarvstedt** [comment]
Done, indeed. Thank you!
