### ISSUE TITLE
different/changing fee estimates

### ISSUE THREAD

**Issue by ndalliard** [fiatjaf/trustedcoin#9]
1. if you type `lightning-cli estimatefees` multiple times - the fees jump from one second to the other. i guess this is because the 3 esplora instances return different feerates
2. the estimates are different from what bitcoind would give as a backend which can lead to some side effects (peers not agreeing on fees for example, leading to closed channels)

the first point i could solve with just using one esplora backend (which kind of makes it less reliable if that backend goes bust, but would be kind of okay) - but i am not sure about the second point. would it be possible to use bitcoind for the estimatefees call and the esplora instances for the rest, especially getting the blocks? i would like to use trustedcoin with a pruned bitcoind backend

i also looked into [btc-rpx-proxy](https://github.com/Kixunil/btc-rpc-proxy) (which would support getting missing blocks), but failed to run it on openbsd

**edit:** maybe i could use something like https://github.com/Toorop/go-bitcoind
**edit2:** maybe i can tweak trustedcoin itself [here](https://github.com/fiatjaf/trustedcoin/blob/master/main.go#L129)  to get similar feerates

**Comment by fiatjaf** [comment]
Yeah, I wanted that too actually. Use bitcoind to publish transactions and estimate fees, but trustedcoin to fetch blocks. However that requires an entirely new plugin.

The default bcli thing to be rewritten and then we just swap out the blocks part for the trustedcoin one. It's easy, but I didn't have time yet.

If you want to tackle that, I would recommend maybe copying code from trustedcoin and from this bcli rewrite: https://github.com/niftynei/glightning/blob/master/examples/plugin/pl_btc/btc.go

**Comment by ndalliard** [comment]
awesome - thanks for the link. i will see what i can do and if it is also easy for me to implement. will update here if i have something to show

**Comment by ndalliard** [comment]
i implemented this in the most reckless way (depending only on blockstream.info and not verifying blocks) - it works for some hours now with my node. will probably add something similar used by trustedcoin (more explorers and validate the blocks): https://git.dalliard.ch/trustme/

will close this, because it is not really an issue with trustedcoin
